export type Product = {
  slug: string;
  name: string;
  category: "Indian" | "Hybrid" | "Global";
  origin: string;
  price: number;
  unit: string;
  sweetness: number; // 1-10
  taste: string;
  season: string;
  image: string;
  description: string;
  notes: string[];
  usage: string[];
};

// Public Unsplash photos of mangoes
const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;

export const products: Product[] = [
  {
    slug: "alphonso",
    name: "Alphonso",
    category: "Indian",
    origin: "Ratnagiri, Maharashtra",
    price: 1200,
    unit: "per dozen",
    sweetness: 10,
    taste: "Rich, creamy, honeyed",
    season: "April – June",
    image: img("photo-1553279768-865429fa0078"),
    description:
      "The King of Mangoes. Saffron-hued flesh, buttery texture and an unmistakable aroma that has defined Indian summers for generations.",
    notes: ["Saffron", "Honey", "Apricot", "Citrus zest"],
    usage: ["Eat fresh", "Aamras", "Mango shrikhand", "Cheesecake"],
  },
  {
    slug: "kesar",
    name: "Kesar",
    category: "Indian",
    origin: "Junagadh, Gujarat",
    price: 950,
    unit: "per dozen",
    sweetness: 9,
    taste: "Saffron-sweet, aromatic",
    season: "May – July",
    image: img("photo-1605027990121-cbae9e0642db"),
    description:
      "Known as the Queen of Mangoes for its bright saffron pulp and balanced sweetness. A favourite for milkshakes and desserts.",
    notes: ["Saffron", "Floral", "Honeyed"],
    usage: ["Milkshakes", "Ice cream", "Kulfi", "Smoothies"],
  },
  {
    slug: "dasheri",
    name: "Dasheri",
    category: "Indian",
    origin: "Malihabad, Uttar Pradesh",
    price: 700,
    unit: "per dozen",
    sweetness: 8,
    taste: "Mild, fragrant, juicy",
    season: "June – August",
    image: img("photo-1591073113125-e46713c829ed"),
    description:
      "Elongated and fragrant, Dasheri is loved across North India for its juicy flesh and gentle, refined sweetness.",
    notes: ["Floral", "Pine", "Light honey"],
    usage: ["Eat fresh", "Juices", "Salads"],
  },
  {
    slug: "langra",
    name: "Langra",
    category: "Indian",
    origin: "Varanasi, Uttar Pradesh",
    price: 750,
    unit: "per dozen",
    sweetness: 8,
    taste: "Tangy-sweet, fibreless",
    season: "July – August",
    image: img("photo-1546173159-315724a31696"),
    description:
      "Greenish even when ripe, Langra is prized for its lemony brightness and smooth, fibreless pulp.",
    notes: ["Lemon", "Pine", "Sweet finish"],
    usage: ["Eat fresh", "Chutneys", "Salsa"],
  },
  {
    slug: "chausa",
    name: "Chausa",
    category: "Indian",
    origin: "Bihar / Uttar Pradesh",
    price: 800,
    unit: "per dozen",
    sweetness: 9,
    taste: "Very sweet, juicy",
    season: "July – August",
    image: img("photo-1622467827417-bbe2237067a9"),
    description:
      "Bright golden-yellow with a deep aroma. Chausa is the closing act of the mango season — sweet, drippy, indulgent.",
    notes: ["Honey", "Vanilla", "Tropical"],
    usage: ["Eat fresh", "Aamras", "Sorbets"],
  },
  {
    slug: "totapuri",
    name: "Totapuri",
    category: "Indian",
    origin: "Karnataka & Andhra Pradesh",
    price: 450,
    unit: "per dozen",
    sweetness: 6,
    taste: "Tangy, mildly sweet",
    season: "May – July",
    image: img("photo-1564355808539-22fda35bed7e"),
    description:
      "Distinctively beak-shaped with a refreshing, tangy profile. The hero of pickles, chutneys and savoury cooking.",
    notes: ["Tangy", "Grassy", "Light sugar"],
    usage: ["Pickles", "Chutney", "Curries", "Salads"],
  },
  {
    slug: "banganapalli",
    name: "Banganapalli",
    category: "Indian",
    origin: "Kurnool, Andhra Pradesh",
    price: 650,
    unit: "per dozen",
    sweetness: 8,
    taste: "Sweet, fibreless, smooth",
    season: "March – June",
    image: img("photo-1605027990121-cbae9e0642db"),
    description:
      "Large, oval and golden — Banganapalli is South India's beloved table mango with thin skin and clean sweet pulp.",
    notes: ["Honey", "Mellow", "Pear"],
    usage: ["Eat fresh", "Fruit bowls", "Smoothies"],
  },
  {
    slug: "neelam",
    name: "Neelam",
    category: "Indian",
    origin: "South India",
    price: 600,
    unit: "per dozen",
    sweetness: 7,
    taste: "Sweet with mild tang",
    season: "June – July",
    image: img("photo-1623930154100-f1a1d0c1d3a4"),
    description:
      "Small, aromatic and late-season — Neelam is famous for its distinctive perfume and balanced taste.",
    notes: ["Floral", "Citrus", "Honey"],
    usage: ["Eat fresh", "Fruit chaat"],
  },
  {
    slug: "himsagar",
    name: "Himsagar",
    category: "Indian",
    origin: "West Bengal",
    price: 900,
    unit: "per dozen",
    sweetness: 9,
    taste: "Creamy, intensely sweet",
    season: "May – June",
    image: img("photo-1591073113125-e46713c829ed"),
    description:
      "Bengal's pride. Fibreless, custard-smooth and intensely sweet — Himsagar is dessert in fruit form.",
    notes: ["Custard", "Honey", "Vanilla"],
    usage: ["Eat fresh", "Aamras", "Mousse"],
  },
  {
    slug: "malgova",
    name: "Malgova",
    category: "Indian",
    origin: "Tamil Nadu",
    price: 850,
    unit: "per dozen",
    sweetness: 9,
    taste: "Rich, dense, sweet",
    season: "June – July",
    image: img("photo-1546173159-315724a31696"),
    description:
      "Round, heavy and deeply flavoured. Malgova has a dense, almost meaty pulp adored across South India.",
    notes: ["Honey", "Caramel", "Tropical"],
    usage: ["Eat fresh", "Ice cream", "Lassi"],
  },
  {
    slug: "badami",
    name: "Badami",
    category: "Indian",
    origin: "Karnataka",
    price: 950,
    unit: "per dozen",
    sweetness: 9,
    taste: "Alphonso-like, smooth",
    season: "April – June",
    image: img("photo-1553279768-865429fa0078"),
    description:
      "Often called the Alphonso of Karnataka. Smooth, rich and aromatic — a Bangalore summer favourite.",
    notes: ["Honey", "Apricot", "Saffron"],
    usage: ["Eat fresh", "Aamras", "Smoothies"],
  },
  {
    slug: "sindhura",
    name: "Sindhura",
    category: "Indian",
    origin: "Andhra Pradesh",
    price: 550,
    unit: "per dozen",
    sweetness: 7,
    taste: "Sweet-tangy, juicy",
    season: "May – June",
    image: img("photo-1622467827417-bbe2237067a9"),
    description:
      "Red-blushed skin and bright yellow pulp. Sindhura is wonderfully juicy with a lively sweet-tangy bite.",
    notes: ["Tangy", "Sweet", "Tropical"],
    usage: ["Juices", "Smoothies", "Salsa"],
  },
  {
    slug: "amrapali",
    name: "Amrapali",
    category: "Hybrid",
    origin: "India (Dasheri × Neelam)",
    price: 700,
    unit: "per dozen",
    sweetness: 9,
    taste: "Deep sweet, aromatic",
    season: "June – August",
    image: img("photo-1564355808539-22fda35bed7e"),
    description:
      "A modern Indian hybrid with deep red pulp, high beta-carotene and an intensely sweet, perfumed flavour.",
    notes: ["Honey", "Floral", "Caramel"],
    usage: ["Eat fresh", "Desserts", "Smoothies"],
  },
  {
    slug: "mallika",
    name: "Mallika",
    category: "Hybrid",
    origin: "India (Neelam × Dasheri)",
    price: 800,
    unit: "per dozen",
    sweetness: 9,
    taste: "Honey-citrus, fibreless",
    season: "June – July",
    image: img("photo-1591073113125-e46713c829ed"),
    description:
      "Smooth, fibreless and packed with a honey-citrus character that wins over chefs and home cooks alike.",
    notes: ["Honey", "Citrus", "Melon"],
    usage: ["Eat fresh", "Sorbets", "Cheesecake"],
  },
  {
    slug: "tommy-atkins",
    name: "Tommy Atkins",
    category: "Global",
    origin: "Florida, USA",
    price: 500,
    unit: "per kg",
    sweetness: 6,
    taste: "Mild, firm, refreshing",
    season: "Year-round (imported)",
    image: img("photo-1623930154100-f1a1d0c1d3a4"),
    description:
      "The world's most exported mango. Firm flesh, mild sweetness and long shelf life make it perfect for travel.",
    notes: ["Mild sweet", "Peach", "Pine"],
    usage: ["Salads", "Salsa", "Grilling"],
  },
  {
    slug: "kent",
    name: "Kent",
    category: "Global",
    origin: "Florida / Mexico / Peru",
    price: 650,
    unit: "per kg",
    sweetness: 8,
    taste: "Rich, juicy, low-fibre",
    season: "Jan – March, Jun – Aug",
    image: img("photo-1605027990121-cbae9e0642db"),
    description:
      "Greenish-yellow with a red blush. Kent is juicy, almost fibreless and considered a premium global table mango.",
    notes: ["Honey", "Peach", "Tropical"],
    usage: ["Eat fresh", "Smoothies", "Desserts"],
  },
  {
    slug: "keitt",
    name: "Keitt",
    category: "Global",
    origin: "USA / Mexico",
    price: 600,
    unit: "per kg",
    sweetness: 7,
    taste: "Sweet-tart, juicy",
    season: "August – October",
    image: img("photo-1546173159-315724a31696"),
    description:
      "Large, green-skinned even when ripe. Keitt offers a sweet-tart, refreshing flavour and minimal fibre.",
    notes: ["Lime", "Honey", "Tropical"],
    usage: ["Salads", "Salsa", "Eat fresh"],
  },
  {
    slug: "ataulfo",
    name: "Ataulfo",
    category: "Global",
    origin: "Mexico",
    price: 700,
    unit: "per kg",
    sweetness: 9,
    taste: "Buttery, honey-sweet",
    season: "March – July",
    image: img("photo-1553279768-865429fa0078"),
    description:
      "Also called Honey or Champagne mango. Small, golden, buttery-smooth with a deep honey-sweet flavour.",
    notes: ["Honey", "Butter", "Apricot"],
    usage: ["Eat fresh", "Smoothies", "Desserts"],
  },
  {
    slug: "carabao",
    name: "Carabao",
    category: "Global",
    origin: "Philippines",
    price: 750,
    unit: "per kg",
    sweetness: 10,
    taste: "Intensely sweet, fragrant",
    season: "March – June",
    image: img("photo-1622467827417-bbe2237067a9"),
    description:
      "The Philippine national mango. Recognised by Guinness as one of the sweetest in the world — pure tropical joy.",
    notes: ["Honey", "Coconut", "Tropical"],
    usage: ["Eat fresh", "Sticky rice", "Sorbets"],
  },
];

export const getProduct = (slug: string) =>
  products.find((p) => p.slug === slug);
